name: 'strange_places_dbt'
version: '1.0.0'

profile: 'strange_places_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  strange_places_dbt:
    stg:
      +materialized: view
      +schema: stg
    ds:
      +materialized: table
      +schema: ds
    marts:
      +materialized: table
      +schema: marts
