strange_places_dbt:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      dbname: strange_places_dwh
      user: admin
      pass: admin
      schema: dbt
      threads: 4
  target: dev
